export const CIRCLE_PROGRESS_DEFAULTS = {
    'backgroundPadding': 0,
    'radius': 14,
    'space': -2,
    'toFixed': 1,
    'maxPercent': 100,
    'outerStrokeWidth': 2,
    'outerStrokeColor': '#fff',
    'innerStrokeColor': 'rgba(232,232,232,0.1)',
    'innerStrokeWidth': 2,
    'titleFontSize': '12px',
    'subtitleFontSize': '8px',
    'animation': false,
    'animateTitle': false,
    'animationDuration': 1000,
    'showTitle': false,
    'showUnits': false,
    'showBackground': false,
};
